export const STORAGE_KEYS = {
  onboarded: "estate-dday:onboarded",
  homeTab: "estate-dday:homeTab",
  buyer: "estate-dday:buyerForm",
  loan: "estate-dday:loanForm",
  loans: "estate-dday:loans",
  prepayments: "estate-dday:prepayments",
};

export const initialBuyer = {
  annualIncome: 45600000,
  spouseAnnualIncome: 0,
  assets: [{ id: "asset-cash", name: "예금/현금", amount: 80000000 }],
  netWorth: 80000000,
  existingDebtMonthly: 0,
  targetHomePriceMode: "auto",
  targetHomePrice: 500000000,
  areaM2: 84,
  married: "single",
  marriageYears: 3,
  firstHome: "yes",
  isHomeless: "yes",
  multiChild: false,
  newborn: false,
  childrenCount: 0,
  birthDate: "",
  region: "normal",
};

export const initialLoans = [
  {
    id: "home-main",
    name: "주택담보대출",
    principal: 280000000,
    rate: 4.2,
    type: "mortgage",
    method: "equalPayment",
    payDay: 25,
    startYear: new Date().getFullYear() - 1,
    startMonth: 5,
    maturityYear: new Date().getFullYear() + 29,
    maturityMonth: 5,
    prepayments: [],
  },
  {
    id: "credit-bridge",
    name: "생활비 신용대출",
    principal: 30000000,
    rate: 5.8,
    type: "credit",
    method: "bullet",
    payDay: 10,
    startYear: new Date().getFullYear(),
    startMonth: 1,
    maturityYear: new Date().getFullYear() + 3,
    maturityMonth: 1,
    prepayments: [],
  },
];
